layout_spectrum: 0.8929174
typography_spectrum: 0.6905565
color:
  saturation: 0.4739074
  lightness: 0.2152246
  brandStrength: 0.4932546
  brandColors:
    - '#FFFFFF'
    - '#E5E4E9'
    - '#BEBEB6'
    - '#967869'
    - '#CDA871'
  rhythmicContrast: 0.4962789
name: 3 Stories Trading Co.
